# OpenGL-Registry
ExternalProject_Add(opengl_registry_project
    GIT_REPOSITORY https://github.com/KhronosGroup/OpenGL-Registry.git
    GIT_TAG main # Or a specific commit/tag for stability
    SOURCE_DIR ${CMAKE_BINARY_DIR}/external/OpenGL-Registry
    BINARY_DIR ${CMAKE_BINARY_DIR}/external/OpenGL-Registry-build # Dummy build dir, not a CMake project
    CONFIGURE_COMMAND "" # No build system to configure
    BUILD_COMMAND ""     # Nothing to build, it's a repository of XML/header files
    INSTALL_COMMAND ""   # Headers/XML are used directly from the source directory
    LOG_DOWNLOAD ON
)

# Interface target for include directories from OpenGL-Registry
# Headers like glcorearb.h, gl.h, KHR/khrplatform.h are usually in a subdirectory like 'api'.
# The spec_parser.c includes headers like "gl_core_3_3.h", which are generated into or exist in "api/GL/".
# The KhronosGroup/OpenGL-Registry repository contains these under the "api/" directory.
add_library(OpenGL-Registry INTERFACE IMPORTED GLOBAL)
target_include_directories(OpenGL-Registry INTERFACE
    ${CMAKE_BINARY_DIR}/external/OpenGL-Registry/api
)
add_dependencies(OpenGL-Registry opengl_registry_project) # Ensure download happens

# Set variables for convenience, e.g., if spec_parser needs path to gl.xml
set(OPENGL_REGISTRY_API_DIR ${CMAKE_BINARY_DIR}/external/OpenGL-Registry/api CACHE PATH "OpenGL-Registry API header directory")
set(OPENGL_REGISTRY_XML_DIR ${CMAKE_BINARY_DIR}/external/OpenGL-Registry/xml CACHE PATH "OpenGL-Registry XML specification directory")

# spec_parser.c needs to find headers like "mgl_hacks.h", "gl_core_3_3.h".
# "gl_core_3_3.h" and similar are expected to be in the OpenGL-Registry/api/GL directory.
# "mgl_hacks.h" is not standard; if it's part of spec_parser's own files, it should be local.
# A quick check of the initial `ls` output shows no `mgl_hacks.h` in `spec_parser/`.
# This header might be one that `spec_parser` itself generates, or it's expected from the registry.
# If it's from the registry, its location needs to be confirmed.
# For now, the include path is set to the general 'api' directory.
# If `gl_core_3_3.h` is in `api/GL`, then includes in spec_parser.c should be `#include <GL/gl_core_3_3.h>`
# or the include path should be `${CMAKE_BINARY_DIR}/external/OpenGL-Registry/api/GL`.
# The current `spec_parser/CMakeLists.txt` links OpenGL-Registry which provides `${CMAKE_BINARY_DIR}/external/OpenGL-Registry/api`.
# So, in `spec_parser.c`, it should be `#include <GL/gl_core_3_3.h>`.
# Let's verify the includes in `spec_parser.c`. If it's `#include "gl_core_3_3.h"`, the current include path might be insufficient
# or it implies those headers are copied directly into the main `api` dir by some process (unlikely for ExternalProject).

# The `spec_parser.c` has includes like:
# #include "mgl_hacks.h"
# #include "gl_core_3_3.h"
# #include "gl_es_2_0.h"
# This implies these headers should be directly findable.
# The OpenGL Registry puts e.g. glcorearb.h in api/GL/glcorearb.h.
# It does *not* typically provide "gl_core_3_3.h" directly in the root of "api/".
# These specific headers ("gl_core_3_3.h", "gl_es_2_0.h") are usually *generated* from gl.xml by a tool like glad, glLoadGen, etc.
# Or they are custom headers.
# The original XCode project might have a build step that generates these or copies them from somewhere.
# The `enum_parser/enum_parser.c` uses `OpenGL-Registry/xml/gl.xml` to generate `enums.h`.
# The `spec_parser/spec_parser.c` likely uses `OpenGL-Registry/xml/gl.xml` to generate function wrappers.

# If "gl_core_3_3.h" and "mgl_hacks.h" are NOT in OpenGL-Registry/api directly, then spec_parser will fail.
# The existing Makefile does: `EXT_DIRS = ./external/OpenGL-Registry` but doesn't show generation of these headers.
# It's possible these headers are expected to be manually placed or generated by another tool outside this build.
# For now, `ExternalOpenGLRegistry.cmake` will make the `api` and `xml` dirs available.
# The `spec_parser/CMakeLists.txt` adds `OpenGL-Registry` (which exposes the `api` dir) to its includes.
# If `gl_core_3_3.h` is in `spec_parser/` or `MGL/include/GL/` it would be found.
# The initial `ls` shows:
# `MGL/include/GL/glcorearb.h` (standard Khronos header)
# `spec_parser/mgl.h`
# `spec_parser/mgl_funcs.c`
# `spec_parser/spec_parser.c`
# No `gl_core_3_3.h` or `mgl_hacks.h` listed in these directories.

# This implies a missing piece in understanding where these headers come from.
# However, the immediate error is the missing `ExternalOpenGLRegistry.cmake` file itself.
# Let's provide it. The build will then proceed and fail at `spec_parser` compilation if these headers are truly missing.
# This is consistent with the GitHub issue: "Ensure tests pass and dependencies are built and linked".
# If `spec_parser` cannot compile, it's a build failure.

# One possibility: the `external/glfw/deps/glad/gl.h` might be a source for some of these, or a similar generated GL loader.
# Or, the project expects them to be generated by running spec_parser itself, but that's a chicken-and-egg if spec_parser needs them to compile.

# For now, this file will make the OpenGL-Registry available.
# The `target_include_directories(OpenGL-Registry INTERFACE ${CMAKE_BINARY_DIR}/external/OpenGL-Registry/api)`
# means that if `gl_core_3_3.h` was, for example, in `OpenGL-Registry/api/gl_core_3_3.h`, it would be found by `#include "gl_core_3_3.h"`.
# If it's in `OpenGL-Registry/api/GL/gl_core_3_3.h`, it would be found by `#include "GL/gl_core_3_3.h"`.
# The `spec_parser.c` uses `#include "gl_core_3_3.h"`. So it expects it directly in an include path.
# The `OpenGL-Registry/api` directory does contain `GL/glcorearb.h` but not `gl_core_3_3.h` directly.
# This means `spec_parser` will likely still have issues finding these specific headers.
# This is a deeper issue with the source project's dependencies that CMake is now exposing.
# The task is to make it compile. If these headers are missing from the repo and not generated by a clear CMake step,
# that's a problem that might require user input or finding where they *should* come from.

# For now, fixing the missing ExternalOpenGLRegistry.cmake file.
# The content provided here is what I'd expect for just fetching the registry.
# The problem of the specific GL headers for spec_parser remains a likely next failure point.Tool output for `create_file_with_block`:
